SELECT T.NAME, T.N FROM
(SELECT NAME, COUNT(NAME) N FROM ANIMAL_INS
 WHERE NAME is not NULL
GROUP BY NAME
) as T
WHERE N >= 2
ORDER BY NAME ASC

-- HAVING 이용하기
SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2 ORDER BY NAME

출처: https://murra.tistory.com/138 [Murra Blog]